name: Create releases from tags

on:
  push:
    tags:
      - v*
      - "!*-alpha*"
    branches:
      - "main"

jobs:
  create_release_from_new_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Create release from new SemVer tag"
        uses: birdcar/actions/create_release@v0.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          timezone: 'America/Chicago'
