name: Lint

on:
  pull_request:

env:
  RAILS_ENV: test

jobs:
  verify:
    uses: gjtorikian/actions/.github/workflows/lint.yml@main
    secrets:
      gh_token: ${{ secrets.GH_BOT_REPO_TOKEN }}
    with:
      node: true
